import { Dimensions, StyleSheet } from 'react-native';
import { ThemeType } from '../../theme';
import { overlays, primitives } from '../../../styles';

const { width } = Dimensions.get('window');
const gap = 12;
const padding = 16;
const cardWidth = (width - padding * 2 - gap) / 2;

const useStyles = (theme: ThemeType) => {
  return StyleSheet.create({
    WorkoutContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginTop: 10,
    },
    absoluteImage: {
      bottom: 0,
      height: '100%',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      width: '100%',
    },
    buttonContent: {
      alignItems: 'center',
      backgroundColor: overlays.pressed.light,
      flex: 1,
      justifyContent: 'center',
      paddingHorizontal: 20,
    },
    cardBg: {
      flex: 1,
    },
    cardContainer: {
      marginHorizontal: 16,
    },
    centralIcon: {
      height: 64,
      width: 64,
    },
    container: {
      backgroundColor: theme.colors.surface,
      flexGrow: 1,
    },
    emptyStateText: {
      color: theme.colors.textPrimary,
      fontSize: 24,
      padding: 20,
      textAlign: 'center',
    },
    exerAiAnalyseButton: {
      borderRadius: 20,
      elevation: 4,
      height: 60,
      marginHorizontal: 18,
      marginVertical: 10,
      overflow: 'hidden',
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    exerciseAll: {
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.textPrimary,
      borderRadius: 10,
      borderWidth: 1,
      color: theme.colors.textPrimary,
      elevation: 3,
      paddingHorizontal: 8,
      shadowColor: theme.colors.textPrimary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
    },
    exerciseCardImage: {
      borderColor: theme.colors.textPrimary,
      borderRadius: 16,
      borderWidth: 1,
      height: 286,
      marginRight: 10,
      overflow: 'hidden',
      width: 286,
    },
    exerciseHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginRight: 12,
    },
    exerciseImageFixed: {
      height: '92%',
      position: 'absolute',
      top: 0,
      width: '100%',
    },
    footer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderTopColor: theme.colors.textPrimary,
      borderTopWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-around',
      padding: 8,
      width: '100%',
    },
    footerCentralButton: {
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    greeting: {
      color: theme.colors.textPrimary,
      fontFamily: 'Agbalumo',
      fontSize: 30,
      fontWeight: '800',
      lineHeight: 30,
      textAlign: 'center',
    },
    header: {
      alignSelf: 'flex-start',
      color: theme.colors.textPrimary,
      fontSize: 22,
      fontWeight: '800',
      margin: 12,
      textAlign: 'left',
    },
    homeContainer: {
      backgroundColor: theme.colors.surface,
      flex: 1,
      paddingBottom: 20,
    },
    homeLoadingContainer: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
    },
    iconBg: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconButton: {
      height: 30,
      width: 30,
    },
    iconKettlebell: {
      alignItems: 'center',
      height: 64,
      justifyContent: 'center',
      width: 64,
    },
    iconKettlebellImage: {
      height: '100%',
      width: '100%',
    },
    kettlebellText: {
      color: theme.colors.white,
      fontSize: 12,
      fontWeight: 'bold',
      marginTop: 18,
    },
    loadingContainer: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
    },
    markAllButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primaryVariant,
      borderRadius: 20,
      elevation: theme.dark ? 5 : 3,
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingVertical: 10,
      shadowColor: theme.colors.onSurface,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: theme.dark ? 0.4 : 0.1,
      shadowRadius: 4,
    },
    markAllText: {
      color: theme.colors.black,
      fontSize: 14,
      fontWeight: '600',
      marginLeft: 6,
    },
    navBar: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderBottomColor: theme.colors.textPrimary,
      borderBottomWidth: 1,
      flexDirection: 'row',
      height: 70,
      justifyContent: 'space-around',
    },
    navButton: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 50,
      padding: 8,
    },
    notificationCard: {
      alignItems: 'flex-start',
      backgroundColor: theme.colors.backgroundOverlay,
      borderRadius: 12,
      elevation: 3,
      flexDirection: 'row',
      margin: 8,
      padding: 16,
      shadowColor: theme.colors.onSurface,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: theme.dark ? 0.3 : 0.05,
      shadowRadius: 6,
    },
    notificationContent: {
      flex: 1,
      marginRight: 16,
    },
    notificationDate: {
      color: theme.colors.textSecondary,
      fontSize: 12,
    },
    notificationHeaderContainer: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    notificationMessage: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 8,
    },
    notificationTitle: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 6,
    },
    notificationsContainer: {
      backgroundColor: theme.colors.surface,
      flex: 1,
    },
    programCard: {
      backgroundColor: theme.colors.secondary,
      borderColor: theme.colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      elevation: 3,
      marginBottom: 16,
      padding: 20,
      shadowColor: theme.colors.onSurface,
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    quickStartCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      elevation: 3,
      height: cardWidth,
      marginBottom: gap,
      overflow: 'hidden',
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      width: cardWidth,
    },
    quickStartCardContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      paddingHorizontal: padding,
    },
    quickStartCardImage: {
      bottom: 0,
      height: '100%',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      width: '100%',
    },
    quickStartCardText: {
      color: primitives.white,
      fontSize: 22,
      fontWeight: 'bold',
      textAlign: 'center',
      textShadowColor: theme.colors.backdrop,
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 3,
    },
    quickStartOverlay: {
      alignItems: 'center',
      backgroundColor: overlays.pressed.light,
      bottom: 0,
      justifyContent: 'center',
      left: 0,
      padding: 10,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    readButton: {
      alignSelf: 'flex-start',
      backgroundColor: theme.dark
        ? `${theme.colors.secondary}30`
        : `${theme.colors.secondary}20`,
      borderRadius: 20,
      marginTop: 2,
      padding: 10,
    },
    selectProgramBackground: {
      alignItems: 'center',
      borderRadius: 24,
      height: 53,
      justifyContent: 'center',
      width: '100%',
    },
    selectProgramText: {
      color: primitives.white,
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
      textShadowColor: theme.colors.backdrop,
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 3,
    },
    seninGozundenCard: {
      borderColor: theme.colors.textPrimary,
      borderRadius: 16,
      borderWidth: 1,
      height: 212,
      marginRight: 10,
      overflow: 'hidden',
      position: 'relative',
      width: 286,
    },
    seninGozundenImage: {
      height: '100%',
      justifyContent: 'space-around',
      padding: 0,
      width: '100%',
    },
    seninGozundenText: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      bottom: 0,
      color: theme.colors.textPrimary,
      fontSize: 18,
      justifyContent: 'center',
      paddingHorizontal: 8,
      position: 'absolute',
      width: '100%',
    },
    streakContainer: {
      alignItems: 'center',
      height: 64,
      justifyContent: 'center',
      width: 64,
    },
    streakTextWrapper: {
      alignItems: 'center',
      bottom: 0,
      justifyContent: 'center',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    title: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderBottomColor: theme.colors.textPrimary,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      minHeight: 64,
      position: 'relative',
    },
    workoutStat: {
      alignItems: 'center',
      flexDirection: 'row',
      marginRight: 10,
    },
    workoutStatLabel: {
      color: theme.colors.textPrimary,
      fontSize: 12,
    },
    workoutStatValue: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    workoutStats: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginTop: 10,
    },
    yourViewCard: {
      borderRadius: 16,
      height: 80,
      marginRight: 0,
      overflow: 'hidden',
      paddingHorizontal: 10,
      position: 'relative',
      width: '100%',
    },
  });
};

export default useStyles;
