import { Dimensions, Platform, StyleSheet } from 'react-native';
import { ThemeType } from '../../theme';
import { overlays } from '../../../styles';

const { width } = Dimensions.get('window');
const SCREEN_PADDING = 20;
const MAIN_WIDTH = width - SCREEN_PADDING * 2;
const COLUMN_WIDTH = (width - 84) / 3;

const useStyles = (theme: ThemeType) => {
  return StyleSheet.create({
    actionButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primaryVariant,
      borderColor: theme.colors.primaryVariant,
      borderRadius: 16,
      borderWidth: 1,
      flex: 1,
      flexDirection: 'row',
      height: 52,
      justifyContent: 'center',
    },
    actionButtonText: {
      color: theme.colors.primary,
      fontSize: 14,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    button: {
      alignItems: 'center',
      backgroundColor: theme.colors.textPrimary,
      borderRadius: 10,
      flex: 1,
      justifyContent: 'center',
      marginBottom: 20,
      marginHorizontal: 10,
      paddingVertical: 20,
    },
    buttonCamera: {
      backgroundColor: theme.colors.secondary,
      borderRadius: 12,
      elevation: 3,
      paddingHorizontal: 24,
      paddingVertical: 12,
      shadowColor: theme.colors.onSurface,
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    buttonDisabled: {
      backgroundColor: theme.colors.surfaceVariant,
      opacity: 0.5,
    },
    buttonGroup: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginVertical: 10,
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    buttonText: {
      color: theme.colors.surface,
      fontSize: 16,
      fontWeight: '600',
    },
    cameraButton: {
      alignSelf: 'center',
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 40,
      elevation: 5,
      height: 80,
      marginLeft: 8,
      position: 'absolute',
      width: 80,
    },
    cameraButtonContainer: {
      bottom: 88,
      position: 'absolute',
    },
    cameraPreview: {
      borderRadius: 10,
      flex: 1,
      overflow: 'hidden',
      width: '100%',
    },
    card: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderRadius: 15,
      elevation: 5,
      height: 90,
      justifyContent: 'center',
      marginBottom: 10,
      marginTop: 5,
      overflow: 'hidden',
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      width: 90,
    },
    cardBorder: {
      borderColor: theme.colors.primary,
      borderWidth: 3,
    },
    cardImage: {
      height: '100%',
      resizeMode: 'cover',
      width: '100%',
    },
    cardText: {
      color: theme.colors.white,
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    cardTextContainer: {
      alignItems: 'center',
      bottom: 0,
      justifyContent: 'center',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    container: {
      backgroundColor: theme.colors.surface,
      flex: 1,
      padding: 16,
    },
    containerCamera: {
      backgroundColor: theme.colors.surface,
      flex: 1,
      padding: 20,
    },
    contentArea: {
      flex: 1,
      marginVertical: 15,
    },
    dashedContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.border,
      borderRadius: 20,
      borderStyle: 'dashed',
      borderWidth: 2,
      height: 200,
      justifyContent: 'center',
      width: '100%',
    },
    emptyStateContainer: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
      marginVertical: 20,
    },
    emptyStateText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      marginTop: 12,
      textAlign: 'center',
    },
    emptyText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      fontStyle: 'italic',
      marginTop: 10,
      textAlign: 'center',
    },
    equipmentCard: {
      alignItems: 'center',
      marginBottom: 15,
      width: COLUMN_WIDTH,
    },
    equipmentNameText: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 8,
      textAlign: 'center',
      width: '90%',
    },
    footerActions: {
      marginTop: 'auto',
      paddingTop: 10,
    },
    footerButton: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    gridWrapper: {
      gap: 10,
      justifyContent: 'flex-start',
      paddingHorizontal: 15,
    },
    headerDetection: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 18,
      flexDirection: 'row',
      height: 64,
      justifyContent: 'center',
      marginBottom: 16,
      padding: 6,
      paddingHorizontal: 16,
    },
    headerDetectionText: {
      color: theme.colors.onPrimary,
      fontSize: 20,
      fontWeight: '700',
      letterSpacing: -0.5,
      textAlign: 'center',
    },
    image: {
      height: '100%',
      position: 'absolute',
      width: '100%',
    },
    imageContainerEquipment: {
      alignItems: 'center',
      backgroundColor: theme.dark
        ? theme.colors.backgroundOverlay
        : theme.colors.surface,
      borderColor: theme.colors.surface,
      borderRadius: 20,
      borderWidth: 1,
      elevation: 2,
      height: COLUMN_WIDTH,
      justifyContent: 'center',
      overflow: 'hidden',
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 5,
      width: COLUMN_WIDTH,
    },
    imageStyle: {
      borderRadius: 22,
      height: '70%',
      width: '70%',
    },
    indexContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      flex: 1,
      justifyContent: 'center',
    },
    infoIcon: {
      color: theme.colors.textPrimary,
      marginRight: 5,
    },
    infoIconButton: {
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 18,
      elevation: 4,
      padding: 8,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
    },
    infoModalActionButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.secondary,
      borderRadius: 16,
      flex: 1,
      justifyContent: 'center',
      marginHorizontal: 6,
      paddingVertical: 12,
    },
    infoModalActionButtonDisabled: {
      backgroundColor: theme.colors.border,
    },
    infoModalActionText: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: '600',
    },
    infoModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.colors.transparent,
    },
    infoModalCloseButton: {
      borderRadius: 16,
      padding: 6,
    },
    infoModalContent: {
      backgroundColor: theme.colors.surface,
      borderRadius: 24,
      elevation: 10,
      padding: 24,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      width: '100%',
    },
    infoModalDescription: {
      color: theme.colors.textSecondary,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 24,
    },
    infoModalFooter: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 8,
    },
    infoModalHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    infoModalIndicator: {
      backgroundColor: theme.colors.border,
      borderRadius: 5,
      height: 10,
      marginHorizontal: 4,
      width: 10,
    },
    infoModalIndicatorActive: {
      backgroundColor: theme.colors.secondary,
      width: 24,
    },
    infoModalIndicatorRow: {
      alignItems: 'center',
      flexDirection: 'row',
    },
    infoModalOverlay: {
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
      padding: 25,
    },
    infoModalTitle: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: '700',
      marginBottom: 12,
    },
    infoRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'flex-start',
      marginBottom: 6,
    },
    infoRowLeft: {
      alignItems: 'center',
      flexDirection: 'row',
      flex: 1,
    },
    infoText: {
      color: theme.colors.textSecondary,
      fontSize: 13,
    },
    labelText: {
      color: theme.colors.textPrimary,
      fontSize: 16,
    },
    labelTextContainer: {
      alignSelf: 'center',
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 8,
      left: 16,
      paddingHorizontal: 16,
      paddingVertical: 8,
      position: 'absolute',
      right: 16,
      top: 16,
      zIndex: 99,
    },
    mainWrapper: {
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.primaryVariant,
      borderRadius: 24,
      borderWidth: 1,
      flex: 1,
      padding: 20,
      ...Platform.select({
        ios: {
          shadowColor: theme.colors.surface,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.05,
          shadowRadius: 10,
        },
        android: {
          elevation: 4,
        },
      }),
    },
    message: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      marginBottom: 30,
      textAlign: 'center',
    },
    optionButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 25,
      flexDirection: 'row',
      marginBottom: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    optionIcon: {
      color: theme.colors.textPrimary,
      height: 20,
      marginRight: 8,
      resizeMode: 'contain',
      width: 20,
    },
    optionLabel: {
      color: theme.colors.textPrimary,
      fontSize: 14,
    },
    optionLabelSelected: {
      color: theme.colors.onPrimary,
    },
    optionSelected: {
      backgroundColor: theme.colors.primary,
    },
    overlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      backgroundColor: theme.colors.backgroundOverlay,
      justifyContent: 'center',
      opacity: 0,
    },
    overlayIcon: {
      backgroundColor: theme.colors.surface,
      borderRadius: 30,
      color: theme.colors.textPrimary,
    },
    photoGrid: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      justifyContent: 'space-between',
    },
    photoItem1: {
      height: 280,
      width: '100%',
    },
    photoItem2: {
      height: 180,
      width: (MAIN_WIDTH - 50) / 2,
    },
    photoItem3: {
      height: 140,
      width: (MAIN_WIDTH - 50) / 2,
    },
    photoItemBase: {
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      overflow: 'hidden',
      position: 'relative',
    },
    photoItemDouble: {
      aspectRatio: 1,
      width: '45%',
    },
    photoItemImage: {
      height: '100%',
      opacity: 0.9,
      width: '100%',
    },
    photoItemQuad: {
      aspectRatio: 1,
      width: '45%',
    },
    photoItemSingle: {
      aspectRatio: 1,
      width: '85%',
    },
    photoItemTriple: {
      aspectRatio: 1,
      width: '30%',
    },
    regionCard: {
      alignItems: 'center',
      aspectRatio: 1,
      borderColor: theme.colors.transparent,
      borderRadius: 12,
      borderWidth: 2,
      justifyContent: 'center',
      overflow: 'hidden',
      width: '100%',
    },
    regionGrid: {
      flexDirection: 'column',
      gap: 10,
      marginVertical: 10,
    },
    regionRow: {
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'space-between',
    },
    regionCardWrap: {
      flex: 1,
    },
    removeButton: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      padding: 1,
      position: 'absolute',
      right: 8,
      top: 8,
    },
    removeButtonInner: {
      alignItems: 'center',
      height: 24,
      justifyContent: 'center',
      width: 24,
    },
    scrollContainer: {
      marginTop: 10,
    },
    scrollContent: {
      flexGrow: 1,
    },
    selectedCard: {
      shadowColor: theme.colors.primary,
      shadowOpacity: 2,
      shadowRadius: 10,
    },
    selectedCardTextContainer: {
      backgroundColor: overlays.focus.light,
    },
    selectedRegionCard: {borderColor: theme.colors.primary },
    slider: {
      height: 40,
      width: '100%',
    },
    sliderContainer: {
      marginVertical: 16,
      paddingHorizontal: 16,
      width: '100%',
    },
    sliderLabel: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      marginTop: 10,
      textAlign: 'center',
    },
    sliderValue: {
      color: theme.colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
    },
    sliderValueContainer: {
      alignItems: 'center',
      marginBottom: 10,
    },
    stackContainer: {
      backgroundColor: theme.colors.surface,
      flexGrow: 1,
    },
    submitButton: {
      backgroundColor: theme.colors.primary,
      height: 56,
      marginHorizontal: 20,
      marginVertical: 20,
    },
    submitButtonDisabled: {
      backgroundColor: theme.colors.border,
    },
    submitButtonIndex: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 18,
      height: 60,
      justifyContent: 'center',
      marginTop: 'auto',
    },
    submitIcon: {
      height: 34,
      width: 34,
    },
    submitText: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    text: {
      color: theme.colors.primary,
      fontSize: 28,
      fontStyle: 'italic',
      fontWeight: 'bold',
      textTransform: 'uppercase',
    },
    title: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderRadius: 18,
      color: theme.colors.onPrimary,
      fontSize: 24,
      fontWeight: 'bold',
      justifyContent: 'center',
      marginBottom: 16,
      padding: 6,
      paddingHorizontal: 16,
      textAlign: 'center',
    },
    titleCamera: {
      color: theme.colors.textPrimary,
      fontSize: 22,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
    },
    titleOverride: {
      alignItems: 'center',
      borderBottomWidth: 1,
      borderColor: theme.colors.primary,
      color: theme.colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
      justifyContent: 'center',
      marginBottom: 16,
      padding: 16,
      textAlign: 'center',
    },
    workoutContainer: {
      marginBottom: 20,
    },
  });
};

export default useStyles;
