import { StyleSheet } from 'react-native';
import { ThemeType } from '../../../theme';
import { overlays } from '../../../../styles';

const useStyles = (theme: ThemeType) => {
  return StyleSheet.create({
    calendar: {
      backgroundColor: theme.colors.backgroundOverlay,
      borderRadius: 16,
      borderWidth: 0,
      elevation: 6,
      marginBottom: 16,
      marginHorizontal: 4,
      padding: 16,
      shadowColor: theme.colors.textPrimary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
    },card: {
      backgroundColor: theme.colors.backgroundOverlay,
      borderRadius: 16,
      borderWidth: 0,
      elevation: 3,
      marginBottom: 16,
      marginHorizontal: 4,
      padding: 16,
      shadowColor: theme.colors.textPrimary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
    },cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    closeBtn: {
      alignItems: 'center',
      backgroundColor: theme.colors.googleRed,
      borderRadius: 20,
      height: 40,
      justifyContent: 'center',
      marginRight: 8,
      width: 40,
    },
    container: {
      backgroundColor: theme.colors.surface,
      flex: 1,
      padding: 16,
    },
    dayCardHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    dayTitle: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
    },
    description: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      marginTop: 8,
    },
    dividerContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      marginVertical: 8,
    },
    dropdownContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      elevation: 5,
      padding: 8,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
      width: '80%',
    },
    dropdownHeader: {
      borderBottomColor: theme.colors.textPrimary,
      borderBottomWidth: 1,
      marginBottom: 8,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    dropdownItem: {
      alignItems: 'center',
      borderRadius: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      paddingVertical: 8,
    },
    dropdownItemActive: {
      backgroundColor: theme.colors.primary,
    },
    dropdownItemText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '500',
    },
    dropdownItemTextActive: {
      color: theme.colors.onPrimary,
      fontWeight: '700',
    },
    dropdownTitle: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    emptyText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      marginVertical: 16,
      textAlign: 'center',
    },
    filterButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceContainer,
      borderColor: theme.colors.surfaceContainer,
      borderRadius: 12,
      borderWidth: 1,
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    filterButtonText: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      marginRight: 4,
    },
    filtersContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'space-between',
      marginBottom: 16,
      paddingHorizontal: 0,
    },
    header: { marginBottom: 16, paddingLeft: 16 },
    infoLabel: { color: theme.colors.textPrimary, fontSize: 13, width: 120 },
    infoRow: { flexDirection: 'row', marginBottom: 6 },
    infoValue: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
    },
    keyboardAvoidingView: {
      flex: 1,
    },
    leftProgram: {
      alignItems: 'center',
      backgroundColor: theme.colors.accent,
      borderRadius: 12,
      elevation: 3,
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
      marginTop: 16,
      paddingHorizontal: 16,
      paddingVertical: 12,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
    },
    leftProgramText: {
      color: theme.colors.onPrimary,
      fontSize: 14,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    line: {
      backgroundColor: theme.colors.textPrimary,
      flex: 1,
      height: 1,
    },
    listContent: {
      paddingBottom: 24,
      paddingHorizontal: 16,
    },
    modalActions: {
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: 12,
    },
    modalBackdrop: {
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
      padding: 16,
    },
    modalBodyContent: {
      padding: 20,
    },
    modalCard: {
      alignSelf: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 24,
      borderWidth: 1,
      maxHeight: '85%',
      overflow: 'hidden',
      width: '90%',
    },
    modalDesc: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      marginVertical: 8,
    },
    modalHeaderContainer: {
      aspectRatio: 16 / 9,
      backgroundColor: theme.colors.surfaceVariant,
      overflow: 'hidden',
      position: 'relative',
    },
    modalImage: {
      height: '100%',
      width: '100%',
    },
    modalLoaderContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceContainer,
      height: '100%',
      justifyContent: 'center',
      width: '100%',
    },
    modalOverlay: {
      alignItems: 'center',
      backgroundColor: overlays.backdrop.light,
      flex: 1,
      justifyContent: 'center',
      padding: 20,
    },
    modalOverlayTitle: {
      color: theme.colors.white,
      fontSize: 22,
      fontStyle: 'italic',
      fontWeight: '900',
    },
    modalPosterBox: {
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 12,
      height: 72,
      justifyContent: 'center',
      margin: 4,
      overflow: 'hidden',
      width: 72,
    },
    modalPosterRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
    },
    modalStatsRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 24,
      marginBottom: 8,
      marginTop: 12,
    },
    modalTitle: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: '800',
    },
    modalTitleOverlay: {
      backgroundColor: overlays.backdrop.light,
      bottom: 0,
      left: 0,
      padding: 20,
      position: 'absolute',
      right: 0,
    },
    newCardContainer: {
      borderRadius: 24,
      elevation: 5,
      flexDirection: 'row',
      height: 180,
      marginBottom: 16,
      overflow: 'hidden',
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      width: '100%',
    },
    newCardContentLeft: {
      backgroundColor: overlays.surfaceOverlay.light,
      flex: 1,
      justifyContent: 'center',
      maxWidth: '70%',
      padding: 20,
      zIndex: 2,
    },
    newCardImagePerson: {
      height: '100%',
      width: '100%',
    },
    newCardImageWrapper: {
      alignItems: 'center',
      bottom: 0,
      height: '100%',
      justifyContent: 'flex-end',
      position: 'absolute',
      right: 0,
      width: '30%',
      zIndex: 1,
    },
    newCardModalStatText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '700',
      paddingRight: 5,
      textTransform: 'capitalize',
    },
    newCardPill: {
      alignSelf: 'flex-start',
      backgroundColor: overlays.hover.light,
      borderRadius: 8,
      marginBottom: 12,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    newCardPillText: {
      color: theme.colors.black,
      fontWeight: '700',
    },
    newCardStatItem: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 6,
    },
    newCardStatText: {
      color: theme.colors.black,
      fontSize: 14,
      fontWeight: '700',
      paddingRight: 5,
      textTransform: 'capitalize',
    },
    newCardStatsRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 16,
    },
    newCardTitle: {
      color: theme.colors.black,
      fontSize: 18,
      fontStyle: 'italic',
      fontWeight: '900',
      lineHeight: 32,
      marginBottom: 16,
    },
    opacity: {
      opacity: 0.6,
    },
    primaryBtn: {
      alignItems: 'center',
      backgroundColor: theme.colors.textPrimary,
      borderRadius: 16,
      elevation: 4,
      justifyContent: 'center',
      marginTop: 12,
      paddingHorizontal: 24,
      paddingVertical: 16,
      shadowColor: theme.colors.textPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    primaryBtnPressed: { opacity: 0.9 },
    primaryBtnText: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: '900',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    primaryBtnWide: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 10,
      flex: 1,
      paddingVertical: 12,
    },
    primaryText: { color: theme.colors.onPrimary, fontWeight: '800' },
    screen: {
      marginBottom: 8,
    },
    scrollView: { flexGrow: 1 },
    statItem: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.textPrimary,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    statText: {
      color: theme.colors.textPrimary,
      fontSize: 12,
      fontWeight: '700',
    },
    subtitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 6,
      textTransform: 'uppercase',
    },
    title: {
      alignSelf: 'center',
      color: theme.colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 20,
    },
    weeklyIcons: {
      alignSelf: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
      marginTop: 8,
      width: '90%',
    },
    workoutName: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: '800',
    },
    workoutStat: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 16,
      marginTop: 8,
    },
  });
};

export default useStyles;
