import { StyleSheet } from 'react-native';
import { ThemeType } from '../../theme';

const useStyles = (theme: ThemeType) => {
  return StyleSheet.create({
    activityLoaderHeader: {
      color: theme.colors.textPrimary,
      fontSize: 26,
      fontWeight: 'bold',
      paddingBottom: 48,
      textAlign: 'center',
    },
    activitySummaryButton: {
      width: '80%',
    },
    addTimeBtn: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      borderColor: theme.colors.backdrop,
      borderRadius: 20,
      borderWidth: 1,
      flex: 1,
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
      paddingVertical: 18,
    },
    animationContainer: {
      alignItems: 'center',
      height: 300,
      justifyContent: 'center',
      width: 300,
    },
    card: {
      borderRadius: 0,
      overflow: 'hidden',
      width: '100%',
    },
    cardContainer: {
      backgroundColor: theme.colors.backgroundOverlay,
      borderColor: theme.colors.divider,
      borderRadius: 20,
      borderWidth: 1,
      marginBottom: 12,
      overflow: 'hidden',
    },
    cardContent: {
      padding: 16,
    },
    cardHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 12,
    },
    cardHeaderActive: {
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: 1,
    },
    centerBlock: {
      alignItems: 'center',
      flex: 1,
      height: '100%',
      justifyContent: 'center',
    },
    centerIcon: {
      height: '100%',
      opacity: 0.7,
      resizeMode: 'contain',
      width: '80%',
    },
    centerIconContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 10,
    },
    checkAnimation: { height: 200, width: 200 },
    closeButton: {
      padding: 5,
    },
    completedItem: {
      opacity: 0.5,
    },
    congratsButton: {
      backgroundColor: theme.colors.primary,
      borderRadius: 8,
      paddingHorizontal: 32,
      paddingVertical: 12,
    },
    congratsButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    congratsContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      flex: 1,
      justifyContent: 'center',
      padding: 20,
    },
    congratsSubtitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      marginBottom: 24,
      marginTop: 8,
      textAlign: 'center',
    },
    congratsText: {
      color: theme.colors.textPrimary,
      fontSize: 28,
      fontWeight: '900',
      marginTop: 20,
    },
    congratsTitle: {
      color: theme.colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
      marginTop: 16,
      textAlign: 'center',
    },
    container: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      flexGrow: 1,
      justifyContent: 'center',
    },
    countText: {
      color: theme.colors.textPrimary,
      fontFamily: 'Poppins',
      fontSize: 28,
      fontWeight: '500',
    },
    countTextResting: {
      color: theme.colors.textPrimary,
      fontSize: 18,
    },
    currentItem: {
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 8,
    },
    descriptionText: {
      color: theme.colors.textPrimary,
      fontSize: 17,
      fontWeight: '500',
      lineHeight: 26,
      paddingVertical: 8,
      textAlign: 'left',
    },
    doneButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 20,
      padding: 18,
      width: '100%',
    },
    doneButtonText: {
      color: theme.colors.white,
      fontSize: 18,
      fontWeight: 'bold',
    },
    exerciseHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    exerciseInfo: {
      display: 'flex',
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
    },
    exerciseInfoContainer: {
      backgroundColor: theme.colors.surface,
      borderTopLeftRadius: 1,
      borderTopRightRadius: 1,
      bottom: '4%',
      left: 0,
      opacity: 0.8,
      padding: 6,
      paddingTop: 1,
      position: 'absolute',
      right: 0,
    },
    exerciseModalContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      flex: 1,
    },
    exerciseSubtitle: {
      color: theme.colors.textSecondary,
      fontSize: 12,
    },
    exerciseTitle: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 2,
    },
    farSideBlock: {
      alignItems: 'center',
      flexDirection: 'column',
      height: '100%',
      justifyContent: 'space-between',
      marginLeft: 12,
    },
    footer: { alignItems: 'center' },
    footerRow: { alignItems: 'center', flexDirection: 'row', gap: 50 },
    fullScreen: {
      backgroundColor: theme.colors.surface,
      flex: 1,
      width: '100%',
    },
    futureItem: {
      opacity: 0.8,
    },
    group: {
      padding: 16,
      width: '90%',
    },
    groupTitle: {
      alignSelf: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 12,
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 16,
      overflow: 'hidden',
      paddingVertical: 8,
      textAlign: 'center',
      width: '100%',
    },
    header: {
      margin: 16,
      overflow: 'hidden',
      width: '100%',
    },
    headerBackgroundImage: {
      bottom: 0,
      height: '100%',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      width: '100%',
    },
    headerContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      height: 150,
      justifyContent: 'center',
      overflow: 'hidden',
      width: '100%',
    },
    headerImage: {
      alignItems: 'center',
      height: 150,
      justifyContent: 'center',
      width: '100%',
    },
    headerImageStyle: {
      resizeMode: 'cover',
    },headerLeft: {
      alignItems: 'center',
      flexDirection: 'row',
      flex: 1,
    },
    headerTitle: {
      backgroundColor: theme.colors.backdrop,
      borderRadius: 8,
      color: theme.colors.white,
      fontSize: 18,
      fontWeight: 'bold',
      maxWidth: '85%',
      paddingHorizontal: 16,
      paddingVertical: 8,
      textAlign: 'center',
      textShadowColor: theme.colors.backdrop,
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 4,
    },
    headerTitlePaused: {
      backgroundColor: theme.colors.backdrop,
      color: theme.colors.onPrimary,
      fontSize: 20,
      fontWeight: 'bold',
    },
    icon: {
      color: theme.colors.textPrimary,
      marginRight: 4,
    },
    iconBox: { borderRadius: 15, marginBottom: 10, padding: 12 },
    iconCircle: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      borderRadius: 20,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    iconText: {
      alignItems: 'center',
      flexDirection: 'row',
    },
    image: {
      height: 300,
      resizeMode: 'cover',
      width: '100%',
    },
    infoContent: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 6,
    },
    infoRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      paddingTop: 32,
    },
    infoText: {
      color: theme.colors.textSecondary,
      fontSize: 16,
      fontWeight: '600',
    },
    metaItem: {
      alignItems: 'center',
      flexDirection: 'column',
    },
    metaText: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: '500',
      paddingTop: 4,
    },
    modalBackdrop: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
      padding: 20,
      paddingVertical: 60,
    },
    modalCloseBtn: {
      padding: 4,
    },
    modalCloseButton: {
      alignSelf: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 8,
      marginTop: 20,
      paddingHorizontal: 20,
      paddingVertical: 10,
    },
    modalCloseText: {
      color: theme.colors.onPrimary,
      fontWeight: '600',
    },
    modalContainer: {
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 16,
      padding: 20,
      width: '85%',
    },
    modalContent: {
      flex: 1,
      minHeight: 120,
      padding: 24,
      paddingBottom: 30,
      paddingTop: 20,
    },
    modalHeader: {
      alignItems: 'center',
      backgroundColor: theme.colors.secondary,
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 24,
    },
    modalItem: {
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: 1,
      flexDirection: 'column',
      paddingVertical: 10,
    },
    modalItemText: {
      fontSize: 16,
      textAlign: 'center',
    },
    modalOverlay: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
    },
    modalScrollContent: {
      alignItems: 'center',
      paddingBottom: 40,
      paddingHorizontal: 20,
    },
    modalScrollView: {
      width: '100%',
    },
    modalTitle: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '700',
      textAlign: 'center',
    },
    navBtn: { opacity: 0.8 },
    nextInfoBadge: {
      backgroundColor: theme.colors.backdrop,
      borderColor: theme.colors.backdrop,
      borderRadius: 30,
      borderWidth: 1,
      paddingHorizontal: 20,
      paddingVertical: 10,
    },
    nextInfoText: {
      color: theme.colors.white,
      fontSize: 14,
      fontWeight: '600',
    },
    overlay: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
      paddingVertical: 20,
    },
    page: {
      backgroundColor: theme.colors.surface,
      flex: 1,
      position: 'relative',
      width: '100%',
    },
    pausedOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      justifyContent: 'center',
      zIndex: 999,
    },
    pausedText: {
      fontSize: 28,
      fontWeight: '600',
      marginBottom: 24,
      textAlign: 'center',
    },
    playPauseBtn: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 35,
      height: 70,
      justifyContent: 'center',
      width: 70,
    },
    pressedState: {
      opacity: 0.7,
      transform: [{ scale: 0.98 }],
    },
    progressBar: {
      backgroundColor: theme.colors.primary,
      borderRadius: 2,
      height: '100%',
      width: '60%',
    },
    progressIndicator: {
      backgroundColor: theme.colors.primaryVariant,
      borderRadius: 2,
      height: 4,
      marginTop: 4,
    },
    restBackgroundImage: {
      alignSelf: 'center',
      height: '80%',
      maxHeight: 600,
      width: '100%',
    },
    restBackgroundImageContainer: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
    },
    restBtnText: {
      color: theme.colors.white,
      fontSize: 16,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    restFooter: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 15,
      justifyContent: 'space-between',
    },
    restHeader: {
      alignItems: 'center',
      marginTop: 20,
    },
    restTimerSubText: {
      color: theme.colors.white,
      fontSize: 22,
      fontWeight: '500',
      marginTop: -10,
    },
    restTimerText: {
      color: theme.colors.white,
      fontSize: 140,
      fontWeight: '900',
      includeFontPadding: false,
    },
    restTitle: {
      color: theme.colors.white,
      fontSize: 48,
      fontWeight: '700',
      letterSpacing: 3,
      marginBottom: 10,
    },
    restingButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.onSurface,
      borderRadius: 32,
      color: theme.colors.onPrimary,
      height: 48,
      justifyContent: 'center',
      width: 164,
    },
    restingButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 18,
      fontWeight: 'bold',
    },
    restingButtonsContainer: {
      alignItems: 'center',
      display: 'flex',
      flexDirection: 'row',
      gap: 32,
      justifyContent: 'center',
      marginTop: 15,
      width: '90%',
    },
    restingContainer: {
      alignItems: 'flex-start',
      backgroundColor: theme.colors.primary,
      flexDirection: 'row',
      height: 170,
      justifyContent: 'center',
      marginTop: 0,
      width: '100%',
    },
    restingExerciseImage: {
      height: '100%',
      resizeMode: 'contain',
      width: '100%',
    },
    restingImageContainer: {
      backgroundColor: theme.colors.border,
      display: 'flex',
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
    },
    restingInfo: {
      display: 'flex',
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
      width: '100%',
    },
    restingText: {
      color: theme.colors.textPrimary,
      fontSize: 30,
      fontWeight: '500',
    },
    restingTextContainer: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    restingTimeText: {
      color: theme.colors.textPrimary,
      fontSize: 30,
      fontWeight: '500',
    },
    resumeBtn: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 35,
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'center',
      paddingHorizontal: 40,
      paddingVertical: 18,
      width: '100%',
    },
    resumeBtnText: {
      color: theme.colors.onPrimary,
      fontSize: 18,
      fontWeight: 'bold',
      letterSpacing: 1,
    },
    scrollContent: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      paddingBottom: 20,
    },
    sectionHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      marginBottom: 4,
    },
    sectionTitle: {
      color: theme.colors.primary,
      fontSize: 13,
      fontWeight: 'bold',
      textTransform: 'uppercase',
    },
    setBadge: {
      alignSelf: 'center',
      backgroundColor: theme.colors.backdrop,
      borderColor: theme.colors.backdrop,
      borderRadius: 20,
      borderWidth: 1,
      marginBottom: 20,
      marginTop: 10,
      paddingHorizontal: 14,
      paddingVertical: 6,
    },
    setCountCompleted: {
      backgroundColor: theme.colors.primary,
      borderRadius: 16,
      height: 6,
      width: 50,
    },
    setCountContainer: {
      alignItems: 'center',
      display: 'flex',
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
      marginTop: 2,
      width: '100%',
    },
    setCountImage: {
      alignItems: 'center',
      height: 80,
      justifyContent: 'center',
      paddingTop: 23,
      width: 80,
    },
    setCountItem: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
    },
    setCountNotCompleted: {
      backgroundColor: theme.colors.textSecondary,
      borderRadius: 16,
      height: 6,
      width: 50,
    },
    setCountText: {
      color: theme.colors.onPrimary,
      fontSize: 14,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    setText: {
      color: theme.colors.white,
      fontSize: 13,
      fontWeight: '700',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
    },
    sideBlock: {
      alignItems: 'center',
      height: '100%',
      justifyContent: 'center',
    },
    skipRestBtn: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 20,
      elevation: 5,
      flex: 1,
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
      paddingVertical: 18,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    statItem: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 6,
    },
    statText: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      fontWeight: '600',
    },
    statsRow: {
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 16,
      paddingBottom: 16,
    },
    stepBadge: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 12,
      height: 24,
      justifyContent: 'center',
      marginRight: 10,
      width: 24,
    },
    stepBadgeText: {
      color: theme.colors.onPrimary,
      fontSize: 11,
      fontWeight: 'bold',
    },
    stepDescription: {
      color: theme.colors.textSecondary,
      flex: 1,
      fontSize: 14,
      lineHeight: 20,
    },
    stepIndex: {
      color: theme.colors.primary,
      fontSize: 14,
      fontWeight: 'bold',
      width: 20,
    },
    stepNumberContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 12,
      height: 24,
      justifyContent: 'center',
      width: 24,
    },
    stepNumberText: {
      color: theme.colors.textPrimary,
      fontSize: 12,
      fontWeight: 'bold',
    },
    stepRow: {
      flexDirection: 'row',
      gap: 8,
    },
    stepsContainer: {
      gap: 12,
    },
    stickyButtonWrap: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderTopColor: theme.colors.textPrimary,
      borderTopWidth: 1,
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
    },
    stoppedImageContainer: {
      alignItems: 'center',
      height: '70%',
      justifyContent: 'flex-end',
      width: '100%',
    },
    subOverlay: {
      alignItems: 'center',
      backgroundColor: theme.colors.backgroundOverlay,
      borderRadius: 8,
      justifyContent: 'center',
      padding: 8,
    },
    subText: {
      color: theme.colors.textSecondary,
      fontSize: 16,
      marginBottom: 40,
      marginTop: 5,
    },
    summarizeBtn: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      borderRadius: 20,
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 15,
      paddingVertical: 8,
    },
    summarizeBtnText: { color: theme.colors.white, fontWeight: '600' },
    summaryGrid: {
      flexDirection: 'row',
      gap: 15,
      marginBottom: 50,
      width: '100%',
    },
    summaryImage: {
      borderRadius: 16,
      height: 96,
      width: 96,
    },
    summaryItem: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      flex: 1,
      padding: 20,
    },
    summaryLabel: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    summaryValue: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: 'bold',
    },
    thumbnail: {
      backgroundColor: theme.colors.surfaceVariant,
      borderRadius: 12,
      height: 48,
      marginRight: 12,
      width: 48,
    },
    timeText: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
    },
    timerContainer: { alignItems: 'center' },
    timerSubText: {
      color: theme.colors.white,
      fontSize: 20,
      marginTop: -20,
      opacity: 0.8,
    },
    timerText: { color: theme.colors.white, fontSize: 90, fontWeight: '900' },
    title: {
      color: theme.dark ? theme.colors.onPrimary : theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '600',
      paddingTop: 8,
      textAlign: 'center',
    },
    titleContainer: {
      flex: 1,
      justifyContent: 'center',
    },
    uiLayer: {
      flex: 1,
      justifyContent: 'space-between',
      paddingHorizontal: 25,
      paddingVertical: 50,
    },
    videoButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 12,
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'center',
      marginBottom: 20,
      paddingVertical: 12,
    },
    videoButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 14,
      fontWeight: 'bold',
    },
    videoErrorText: {
      color: theme.colors.onPrimary,
      marginTop: 20,
      textAlign: 'center',
    },
    videoModalContent: {
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 24,
      elevation: 5,
      overflow: 'hidden',
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      width: '90%',
    },
    videoModalExArea: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: 'bold',
    },
    videoModalHeader: {
      alignItems: 'center',
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 16,
    },
    videoModalOverlay: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
    },
    videoModalTextXsmall: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: 'bold',
    },
    videoModalTextsmall: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    videoModalTitle: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 16,
      fontWeight: 'bold',
    },
    videoModalTopArea: {
      alignItems: 'center',
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 15,
    },
    videoPlayer: {
      height: '100%',
      width: '100%',
    },
    videoWrapper: {
      aspectRatio: 9 / 16,
      backgroundColor: theme.colors.onSurface,
    },
    workoutInfoContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      marginTop: 10,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    workoutMeta: {
      alignItems: 'center',
      backgroundColor: theme.dark
        ? theme.colors.textSecondary
        : theme.colors.surface,
      borderBottomWidth: 1,
      borderColor: theme.dark ? theme.colors.onSurface : theme.colors.textPrimary,
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 16,
    },
    workoutName: {
      color: theme.colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
      textAlign: 'center',
    },
  });
};

export default useStyles;
