import {StyleSheet} from 'react-native';
import {ThemeType} from '../../../theme';

const useStyles = (theme: ThemeType) => {
  return StyleSheet.create({
    accentBar: {
      backgroundColor: theme.colors.primary,
      bottom: 0,
      left: 0,
      position: 'absolute',
      top: 0,
      width: 4,
    },
    acceptButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.secondary,
      borderRadius: 20,
      elevation: 3,
      height: 40,
      justifyContent: 'center',
      shadowColor: theme.colors.secondary,
      shadowOpacity: 0.3,
      shadowRadius: 4,
      width: 40,
    },
    actionsSection: {
      alignItems: 'center',
      marginVertical: 28,
    },
    addButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 20,
      elevation: 3,
      height: 40,
      justifyContent: 'center',
      shadowColor: theme.colors.primary,
      shadowOpacity: 0.3,
      shadowRadius: 4,
      width: 40,
    },
    backButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderRadius: 20,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    badge: {
      alignItems: 'center',
      backgroundColor: theme.colors.accent,
      borderRadius: 12,
      height: 24,
      justifyContent: 'center',
      minWidth: 24,
      paddingHorizontal: 6,
      position: 'absolute',
      right: -8,
      top: -8,
    },
    badgeText: {
      color: theme.colors.onPrimary,
      fontSize: 12,
      fontWeight: 'bold',
    },
    chip: {
      alignItems: 'center',
      backgroundColor: theme.dark ? theme.colors.onSurface : theme.colors.surfaceContainer,
      borderColor: theme.colors.border,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: 'row',
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    chipMuted: {
      backgroundColor: theme.colors.border,
      borderWidth: 0,
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 12,
    },
    chipText: {
      color: theme.colors.black,
      fontSize: 12,
      fontWeight: '600',
      marginLeft: 6,
    },
    closeButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderRadius: 20,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    container: {
      backgroundColor: theme.colors.surface,
      flex: 1,
    },
    content: {
      flex: 1,
      paddingHorizontal: 20,
    },
    declineButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.accent,
      borderRadius: 20,
      elevation: 3,
      height: 40,
      justifyContent: 'center',
      shadowColor: theme.colors.accent,
      shadowOpacity: 0.3,
      shadowRadius: 4,
      width: 40,
    },
    emptyRequestsState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
      paddingVertical: 64,
    },
    emptyRequestsText: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '600',
      marginTop: 16,
      textAlign: 'center',
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
      paddingVertical: 48,
    },
    emptyStateSubtext: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      marginTop: 8,
      textAlign: 'center',
    },
    emptyStateText: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '600',
      marginTop: 16,
      textAlign: 'center',
    },
    friendsListSection: {
      marginBottom: 24,
    },
    friendsSection: {
      marginBottom: 16,
    },
    header: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingBottom: 16,
      paddingHorizontal: 20,
      paddingTop: 20,
    },
    headerActions: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
    },
    headerIconButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 24,
      elevation: 4,
      height: 48,
      justifyContent: 'center',
      position: 'relative',
      shadowColor: theme.colors.primary,
      shadowOpacity: 0.3,
      shadowRadius: 8,
      width: 48,
    },
    headerSpacer: {
      width: 40,
    },
    headerTitle: {
      color: theme.colors.textPrimary,
      fontSize: 28,
      fontWeight: 'bold',
    },
    infoCard: {
      backgroundColor: theme.dark ? theme.colors.onSurface : theme.colors.surfaceContainer,
      borderColor: theme.colors.border,
      borderRadius: 16,
      borderWidth: 1,
      elevation: 3,
      marginTop: 20,
      padding: 20,
      shadowColor: theme.colors.onSurface,
      shadowOpacity: 0.06,
      shadowRadius: 10,
    },
    infoContent: { flex: 1 },
    infoIcon: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderRadius: 20,
      height: 40,
      justifyContent: 'center',
      marginRight: 12,
      width: 40,
    },
    infoItem: {
      alignItems: 'center',
      flexDirection: 'row',
      marginBottom: 16,
    },
    infoLabel: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: '500',
      marginBottom: 2,
    },
    infoValue: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '600',
    },
    modalContainer: {
      backgroundColor: theme.colors.surface,
      flex: 1,
    },
    modalContent: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 20,
    },
    modalHeader: {
      alignItems: 'center',
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingBottom: 16,
      paddingHorizontal: 20,
      paddingTop: 20,
    },
    modalTitle: {
      color: theme.colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
    },
    nonFriendsSection: {
      marginBottom: 16,
    },
    pendingButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderColor: theme.colors.border,
      borderRadius: 20,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      height: 40,
      justifyContent: 'center',
      minWidth: 40,
      paddingHorizontal: 12,
    },
    pendingButtonText: {
      color: theme.colors.textSecondary,
      fontSize: 13,
      fontWeight: '600',
    },
    profileCard: {
      backgroundColor: theme.dark ? theme.colors.onSurface : theme.colors.surfaceContainer,
      borderColor: theme.colors.border,
      borderRadius: 20,
      borderWidth: 1,
      elevation: 3,
      marginTop: 20,
      padding: 20,
      shadowColor: theme.colors.onSurface,
      shadowOpacity: 0.06,
      shadowRadius: 10,
    },
    profileImage: { height: '100%', width: '100%' },
    profileImageContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 36,
      elevation: 4,
      height: 72,
      justifyContent: 'center',
      marginRight: 16,
      overflow: 'hidden',
      shadowColor: theme.colors.primary,
      shadowOpacity: 0.18,
      shadowRadius: 8,
      width: 72,
    },
    profileImagePlaceholder: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      height: '100%',
      justifyContent: 'center',
      width: '100%',
    },
    profileName: {
      color: theme.colors.black,
      fontSize: 18,
      fontWeight: 'bold',
    },
    profileRow: {
      alignItems: 'center',
      flexDirection: 'row',
    },
    profileSub: {
      color: theme.colors.textSecondary,
      fontSize: 13,
      marginTop: 4,
    },
    removeButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.accent,
      borderRadius: 20,
      elevation: 3,
      height: 40,
      justifyContent: 'center',
      shadowColor: theme.colors.accent,
      shadowOpacity: 0.3,
      shadowRadius: 4,
      width: 40,
    },
    requestActions: {
      flexDirection: 'row',
      gap: 12,
    },
    requestCard: {
      alignItems: 'center',
      backgroundColor: theme.colors.backgroundOverlay,
      borderColor: theme.colors.border,
      borderRadius: 16,
      borderWidth: 1,
      elevation: 3,
      flexDirection: 'row',
      marginBottom: 12,
      padding: 16,
      shadowColor: theme.colors.onSurface,
      shadowOpacity: 0.08,
      shadowRadius: 8,
    },
    searchButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 20,
      height: 40,
      justifyContent: 'center',
      marginLeft: 12,
      width: 40,
    },
    searchButtonDisabled: {
      backgroundColor: theme.colors.border,
    },
    searchContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceContainer,
      borderColor: theme.colors.border,
      borderRadius: 16,
      borderWidth: 1,
      elevation: 3,
      flexDirection: 'row',
      marginBottom: 16,
      paddingHorizontal: 16,
      paddingVertical: 12,
      shadowColor: theme.colors.onSurface,
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    searchIcon: {
      marginRight: 12,
    },
    searchInput: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 16,
      paddingVertical: 4,
    },
    searchResultsSection: {
      marginBottom: 24,
    },
    searchSection: {
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    sectionTitle: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 16,
      marginTop:10,
    },
    statCard: {
      backgroundColor: theme.dark ? theme.colors.onSurface : theme.colors.surfaceContainer,
      borderBottomLeftRadius: 0,
      borderColor: theme.colors.border,
      borderRadius: 16,
      borderTopLeftRadius: 0,
      borderWidth: 1,
      elevation: 3,
      padding: 16,
      position: 'relative',
      shadowColor: theme.colors.onSurface,
      shadowOpacity: 0.06,
      shadowRadius: 10,
      width: '48%',
    },
    statIconWrap: {
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceContainer,
      borderColor: theme.colors.border,
      borderRadius: 20,
      borderWidth: 1,
      height: 40,
      justifyContent: 'center',
      marginBottom: 10,
      width: 40,
    },
    statLabel: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    statValue: {
      color: theme.colors.black,
      fontSize: 18,
      fontWeight: 'bold',
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    subsectionTitle: {
      color: theme.colors.textSecondary,
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 12,
      marginTop: 8,
    },
    subtleDangerButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.transparent,
      borderColor: theme.colors.border,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    subtleDangerText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      fontWeight: '600',
    },
    toggleButton: {
      alignItems: 'center',
      borderRadius: 8,
      flex: 1,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    toggleButtonActive: {
      backgroundColor: theme.colors.surfaceContainer,
      elevation: 2,
      shadowColor: theme.colors.onSurface,
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    toggleContainer: {
      backgroundColor: theme.colors.border,
      borderRadius: 12,
      flexDirection: 'row',
      padding: 4,
    },
    toggleText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      fontWeight: '600',
    },
    toggleTextActive: {
      color: theme.colors.primary,
    },
    userAvatar: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 28,
      height: 56,
      justifyContent: 'center',
      marginRight: 16,
      overflow: 'hidden',
      width: 56,
    },
    userAvatarImage: {
      height: '100%',
      width: '100%',
    },
    userCard: {
      alignItems: 'center',
      backgroundColor: theme.colors.backgroundOverlay,
      borderColor: theme.colors.border,
      borderRadius: 16,
      borderWidth: 1,
      elevation: 3,
      flexDirection: 'row',
      marginBottom: 12,
      padding: 16,
      shadowColor: theme.colors.onSurface,
      shadowOpacity: 0.08,
      shadowRadius: 8,
    },
    userEmail: {
      color: theme.colors.textSecondary,
      fontSize: 14,
    },
    userInfo: {
      flex: 1,
    },
    userInitials: {
      color: theme.colors.onPrimary,
      fontSize: 20,
      fontWeight: 'bold',
    },
    userName: {
      color: theme.colors.black,
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 4,
    },
  });
};

export default useStyles;
