import { Dimensions, StyleSheet } from 'react-native';
import { ThemeType } from '../src/theme';
import { primitives } from '../styles';

const { height: screenHeight } = Dimensions.get('window');

const useStyles = (theme: ThemeType) => {
  return StyleSheet.create({
    accordionAnswer: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    accordionContent: {
      paddingTop: 0,
      padding: 16,
    },
    accordionHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 16,
    },
    accordionHeaderActive: {
      borderBottomColor: theme.dark
        ? theme.colors.divider
        : theme.colors.divider,
      borderBottomWidth: 1,
    },
    accordionItem: {
      backgroundColor: theme.colors.backgroundOverlay,
      borderRadius: 12,
      marginBottom: 10,
    },
    accordionQuestion: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 15,
      fontWeight: '600',
      marginRight: 10,
    },
    activeDot: {
      backgroundColor: theme.colors.primary,
    },
    awardContainer: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    awardTextContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
      zIndex: 1,
    },
    button: {
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 10,
      flexDirection: 'row',
      height: '100%',
      justifyContent: 'center',
      width: '100%',
    },
    buttonContainer: {
      alignItems: 'center',
      borderColor: theme.colors.warning,
      borderRadius: 18,
      borderWidth: 4,
      height: 68,
      justifyContent: 'center',
      marginHorizontal: 20,
      padding: 3,
      width: 320,
    },
    buttonIcon: {
      paddingRight: 8,
    },
    buttonLabel: {
      color: theme.colors.onPrimary,
      fontSize: 16,
    },
    buttonText: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 16,
    },
    card: {
      alignItems: 'center',
      borderRadius: 16,
      elevation: 8,
      flexDirection: 'row',
      marginVertical: 8,
      paddingHorizontal: 16,
      paddingVertical: 14,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.18,
      shadowRadius: 12,
    },
    cardContainer: {
      backgroundColor: theme.colors.textSecondary,
      borderRadius: 12,
      marginRight: 10,
      overflow: 'hidden',
      width: 160,
    },
    changeText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 2,
      marginLeft: 8,
    },
    chart: { borderRadius: 16, marginTop: 6 },
    chartTitle: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      fontWeight: '600',
      marginBottom: 10,
    },
    chartWrapper: {
      backgroundColor: theme.colors.surfaceVariant,
      borderRadius: 16,
      elevation: 8,

      marginBottom: 32,
      marginTop: 8,
      padding: 16,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.18,
      shadowRadius: 12,
    },
    closeButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 5,
      marginTop: 20,
      padding: 10,
    },
    closeButtonText: {
      color: theme.colors.onPrimary,
      fontWeight: 'bold',
    },
    contactContainer: {
      padding: 16,
    },
    container: {
      marginBottom: 16,
    },
    contentContainer: {
      flex: 1,
      justifyContent: 'center',
      marginLeft: 44,
      marginRight: 12,
    },
    detail: {
      alignItems: 'center',
      flexDirection: 'row',
      marginBottom: 2,
    },
    detailText: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      marginLeft: 4,
    },
    detailsContainer: {
      flexDirection: 'column',
      flexWrap: 'wrap',
      marginTop: 4,
    },
    divider: {
      backgroundColor: theme.colors.surfaceVariant,
      height: 1,
      marginVertical: 20,
    },
    gradientShadow: {
      bottom: 0,
      height: 4,
      left: 0,
      opacity: 0.6,
      position: 'absolute',
      right: 0,
    },
    header: {
      alignItems: 'center',
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 15,
      paddingBottom: 10,
    },
    icon: {
      backgroundColor: theme.colors.primary,
      color: theme.colors.onPrimary,
    },
    iconContainer: {
      paddingLeft: 10,
    },
    iconWrap: {
      alignItems: 'center',
      borderRadius: 12,
      elevation: 5,
      height: 44,
      justifyContent: 'center',
      marginRight: 14,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      width: 44,
    },
    iconwrapper: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 30,
      color: theme.colors.onPrimary,
      height: 48,
      justifyContent: 'center',
      marginRight: 16,
      width: 48,
    },
    image: {
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
      height: 100,
      width: '100%',
    },
    imageContainer: {
      position: 'relative',
    },
    inactiveDot: {
      backgroundColor: theme.colors.border,
    },
    input: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 16,
      paddingVertical: 8,
    },
    inputGroup: {
      marginBottom: 20,
    },
    inputLabel: {
      color: theme.colors.primary,
      fontSize: 15,
      marginBottom: 8,
    },
    inputWrapper: {
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 15,
      elevation: 3,
      flexDirection: 'row',
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    loader: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: theme.colors.surface,
      flex: 1,
      height: '100%',
      justifyContent: 'center',
      width: '100%',
    },
    modalContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
    },
    modalContent: {
      backgroundColor: theme.colors.surface,
      borderRadius: 10,
      maxHeight: '80%',
      padding: 20,
      width: '80%',
    },
    modalScrollContent: {
      paddingBottom: 10,
    },
    modalScrollView: {
      maxHeight: '100%',
    },
    modalText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
    },
    modalTitle: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 10,
      textAlign: 'center',
    },
    normBtn: {
      alignItems: 'center',
      borderColor: theme.colors.border,
      borderRadius: 10,
      borderWidth: 1,
      justifyContent: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    normText: {
      fontSize: 11,
      fontWeight: 'bold',
    },
    overlay: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
    },
    passwordRuleIcon: {
      alignItems: 'center',
      marginRight: 8,
      width: 16,
    },
    passwordRuleItem: {
      alignItems: 'flex-start',
      flexDirection: 'column',
      marginVertical: 6,
    },
    passwordRuleText: {
      color: theme.dark ? theme.colors.onPrimary : theme.colors.textPrimary,
      flex: 1,
      fontSize: 11,
      lineHeight: 16,
    },
    passwordRulesContainer: {
      backgroundColor: theme.colors.backdrop,
      borderColor: theme.colors.textPrimary,
      borderRadius: 12,
      borderWidth: 1,
      marginBottom: 8,
      marginTop: 8,
      padding: 12,
    },
    passwordRulesTitle: {
      color: theme.colors.primary,
      fontSize: 12,
      fontWeight: '600',
      marginBottom: 8,
    },
    playButton: {
      backgroundColor: theme.colors.primary,
      borderRadius: 20,
      bottom: -16,
      padding: 6,
      position: 'absolute',
      right: 4,
    },
    pressedState: {
      opacity: 0.7,
      transform: [{ scale: 0.98 }],
    },
    profileButton: {
      alignItems: 'center',
      flexDirection: 'row',
      paddingVertical: 16,
    },
    progressDot: {
      borderRadius: 5,
      height: 10,
      marginHorizontal: 5,
      width: 10,
    },
    progressIndicator: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginVertical: 20,
    },
    radioIcon: {
      color: theme.colors.primary,
    },
    radioText: {
      color: theme.colors.textPrimary,
      fontSize: 16,
    },
    radiobutton: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 25,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 15,
      padding: 15,
    },
    rankText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: 'bold',
      includeFontPadding: false,
      marginTop: -8,
      textAlign: 'center',
      textAlignVertical: 'center',
    },
    rnCloseButton: {
      padding: 5,
    },
    rnCloseButtonText: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
    },
    rnModalContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: 8,
      elevation: 2,
      padding: 20,
      width: '80%',
    },
    roundedButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 100,
      marginVertical: 16,
      paddingVertical: 16,
    },
    roundedButtonDisabled: {
      backgroundColor: theme.colors.border,
      opacity: 0.65,
    },
    roundedButtonPressed: { opacity: 0.8, transform: [{ scale: 0.96 }] },
    roundedButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 18,
      fontWeight: 'bold',
    },
    scrollView: { maxHeight: screenHeight * 0.5 },
    searchBox: {
      backgroundColor: theme.colors.surface,
      borderRadius: 25,
      color: theme.colors.textPrimary,
      fontSize: 16,
      marginBottom: 15,
      paddingHorizontal: 20,
      paddingVertical: 10,
    },
    segmentSwitchButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderRadius: 20,
      flex: 1,
      justifyContent: 'center',
      marginHorizontal: 4,
      padding: 10,
    },
    segmentSwitchButtonSelected: {
      backgroundColor: theme.colors.primary,
    },
    segmentSwitchContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 20,
    },
    segmentSwitchText: {
      color: theme.colors.primary,
      fontSize: 16,
      fontWeight: '500',
    },
    segmentSwitchTextSelected: {
      color: theme.colors.onPrimary,
    },
    segmentedButton: {
      alignItems: 'center',
      backgroundColor: primitives.slate300,
      borderColor: theme.colors.transparent,
      borderRadius: 25,
      borderWidth: 1,
      justifyContent: 'center',
      marginVertical: 10,
      paddingHorizontal: 20,
      paddingVertical: 15,
    },
    segmentedButtonSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
      borderRadius: 25,
      elevation: 3,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
    },
    segmentedButtonText: {
      color: theme.dark ? theme.colors.onPrimary : theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: '500',
    },
    segmentedButtonTextSelected: {
      color: theme.colors.onPrimary,
    },
    starBadge: {
      backgroundColor: theme.colors.textSecondary,
      borderRadius: 8,
      padding: 2,
      position: 'absolute',
      right: 8,
      top: 12,
    },
    statItem: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 5,
    },
    statText: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      fontWeight: '600',
    },
    statsContainer: {
      alignItems: 'center',
      columnGap: 12,
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 2,
      rowGap: 6,
    },
    suffix: {
      fontSize: 12,
      marginBottom: 3,
      marginLeft: 4,
    },
    tabActive: {
      borderColor: theme.colors.textPrimary,
      borderRadius: 12,
      borderWidth: 1,
      marginHorizontal: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    tabButtons: {
      alignSelf: 'flex-start',
      backgroundColor: theme.colors.surfaceVariant,
      borderRadius: 12,
      flexDirection: 'row',
      padding: 4,
    },
    tabContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    tabIdle: {
      backgroundColor: theme.colors.backdrop,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    tabText: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      fontWeight: '700',
    },
    tabs: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      marginBottom: 4,
      paddingHorizontal: 12,
    },
    textCol: {
      flex: 1,
      justifyContent: 'center',
    },
    textContainer: {
      padding: 8,
    },
    tfCard: {
      alignItems: 'center',
      backgroundColor: theme.colors.backgroundOverlay,
      borderColor: theme.colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      elevation: 2,
      flexDirection: 'row',
      minHeight: 96,
      overflow: 'hidden',
      padding: 12,
      position: 'relative',
      shadowColor: theme.colors.backdrop,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
    },
    tfImage: {
      height: '100%',
      width: '100%',
    },
    tfImageContainer: {
      backgroundColor: theme.colors.border,
      borderRadius: 12,
      height: 76,
      overflow: 'hidden',
      width: 76,
    },
    tfTitle: {
      color: theme.colors.textPrimary,
      fontSize: 17,
      fontWeight: 'bold',
      marginBottom: 6,
      marginTop: 2,
    },
    title: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      fontWeight: '800',
      marginVertical: 6,
    },
    value: {
      fontSize: 22,
      fontWeight: '800',
    },

    valueRow: {
      alignItems: 'flex-end',
      flexDirection: 'row',
    },

    versionDate: {
      color: theme.colors.textSecondary,
      fontSize: 12,
    },

    versionHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 5,
    },

    versionItem: {
      marginBottom: 20,
    },

    versionNumber: {
      color: theme.colors.primary,
      fontSize: 16,
      fontWeight: 'bold',
    },

    wrap: { borderRadius: 16, paddingVertical: 10 },
  });
};

export default useStyles;
