import { StyleSheet } from 'react-native';
import { ThemeType } from '../../theme';

const useStyles = (theme: ThemeType) => {
  return StyleSheet.create({
    accordionAnswer: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    accordionHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 16,
    },
    accordionItem: {
      backgroundColor: theme.colors.backgroundOverlay,
      borderRadius: 12,
      marginBottom: 10,
    },
    accordionQuestion: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 15,
      fontWeight: '600',
      marginRight: 10,
    },
    accountActionsContainer: {
      gap: 12,
    },
    alertButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.textSecondary,
      borderRadius: 14,
      elevation: 3,
      flex: 1,
      justifyContent: 'center',
      paddingVertical: 14,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    alertContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.primary,
      borderRadius: 20,
      borderWidth: 1,
      padding: 16,
      width: '85%',
    },
    badge: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 999,
      marginBottom: 6,
      minWidth: 60,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    badgeMuted: {
      backgroundColor: theme.dark
        ? theme.colors.border
        : theme.colors.surface,
      borderColor: theme.colors.border,
      borderWidth: 1,
    },
    badgeMutedText: {
      color: theme.colors.textSecondary,
    },
    badgeText: {
      color: theme.colors.onPrimary,
      fontSize: 11,
      fontWeight: '600',
      textTransform: 'uppercase',
    },
    blackButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 25,
      marginTop: 20,
      paddingVertical: 15,
    },
    blackButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    button: {
      alignItems: 'center',
      flexDirection: 'row',
      paddingVertical: 16,
    },
    buttonContainer: {
      flexDirection: 'row',
      gap: 16,
      marginTop: 10,
      paddingHorizontal: 10,
      width: '100%',
    },
    cancelButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    confirmButton: {
      alignSelf: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 25,
      elevation: 3,
      marginBottom: 30,
      paddingHorizontal: 25,
      paddingVertical: 12,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    confirmButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    contactContainer: {
      alignItems: 'center',
      paddingVertical: 20,
    },
    contactHeading: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 8,
    },
    contactLink: {
      color: theme.colors.primary,
      fontSize: 15,
      marginBottom: 16,
      textDecorationLine: 'underline',
    },
    contactText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
    },
    container: {
      backgroundColor: theme.colors.surface,
      flex: 1,
      paddingHorizontal: 16,
    },
    content: {
      flexGrow: 1,
      paddingBottom: 32,
      paddingHorizontal: 16,
      paddingTop: 24,
    },
    deactivateButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.googleRed,
      borderRadius: 8,
      marginTop: 12,
      paddingVertical: 12,
    },
    deactivateButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 14,
      fontWeight: '600',
    },
    deactivateContent: {
      paddingTop: 0,
      padding: 16,
    },
    divider: {
      backgroundColor: theme.colors.surfaceContainer,
      marginHorizontal: 8,
      width: 1,
    },
    editIconBadge: {
      alignItems: 'center',
      backgroundColor: theme.colors.onSurface,
      borderColor: theme.colors.surface,
      borderRadius: 18,
      borderWidth: 3,
      bottom: 5,
      elevation: 4,
      height: 36,
      justifyContent: 'center',
      position: 'absolute',
      right: 0,
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      width: 36,
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
      paddingVertical: 24,
    },
    emptyStateText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      textAlign: 'center',
    },
    faqHeaderContainer: {
      gap: 16,
      marginBottom: 20,
      paddingVertical: 8,
    },
    faqListContainer: {
      paddingBottom: 40,
    },
    formBlock: {
      backgroundColor: theme.colors.primary,
      borderRadius: 16,
      marginBottom: 20,
      padding: 16,
    },
    heading: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 10,
      marginTop: 16,
    },
    id: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontStyle: 'italic',
    },
    infoBlock: {
      backgroundColor: theme.colors.primary,
      borderRadius: 12,
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 16,
      padding: 12,
    },
    infoItem: {
      alignItems: 'center',
    },
    infoLabel: {
      color: theme.colors.surface,
      fontSize: 12,
    },
    infoValue: {
      color: theme.colors.onPrimary,
      fontSize: 18,
      fontWeight: 'bold',
    },
    input: {
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 10,
      fontSize: 16,
      marginBottom: 10,
      padding: 10,
    },
    inputCardContainer: {
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.primary,
      borderRadius: 20,
      borderWidth: 0.5,
      elevation: 12,
      marginTop: 60,
      padding: 25,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.9,
      shadowRadius: 20,
    },
    label: {
      color: theme.colors.onPrimary,
      fontWeight: 'bold',
      marginBottom: 4,
      marginTop: 12,
    },
    languageAvatar: {
      alignItems: 'center',
      backgroundColor: theme.dark
        ? theme.colors.border
        : theme.colors.surface,
      borderRadius: 22,
      height: 44,
      justifyContent: 'center',
      marginRight: 16,
      width: 44,
    },
    languageAvatarText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: 'bold',
      textTransform: 'uppercase',
    },
    languageCard: {
      backgroundColor: theme.dark ? theme.colors.surfaceVariant : theme.colors.surfaceContainer,
      borderColor: theme.colors.border,
      borderRadius: 18,
      borderWidth: 1,
      marginBottom: 24,
      paddingHorizontal: 4,
      paddingVertical: 4,
    },
    languageInfo: {
      flex: 1,
    },
    languageMeta: {
      alignItems: 'flex-end',
      marginLeft: 12,
    },
    languageName: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: '600',
    },
    languageNative: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      marginTop: 2,
    },
    languageRegion: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      marginTop: 4,
    },
    languageRow: {
      alignItems: 'center',
      borderRadius: 14,
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    languageRowSelected: {
      backgroundColor: theme.colors.border,
      borderColor: theme.colors.primary,
      borderRadius: 14,
      borderWidth: 1,
    },
    languageSubtitle: {
      alignSelf: 'flex-start',
      marginBottom: 24,
    },
    languageTitle: {
      alignSelf: 'flex-start',
      marginBottom: 8,
    },
    layoutContainer: {
      backgroundColor: theme.colors.surfaceContainer,
      flexGrow: 1,
    },
    linkText: {
      color: theme.colors.textPrimary,
      fontSize: 12,
      textDecorationLine: 'underline',
    },
    message: {
      color: theme.colors.textSecondary,
      fontSize: 16,
      lineHeight: 22,
      marginBottom: 24,
      textAlign: 'center',
    },
    overlay: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
    },
    paragraph: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'justify',
    },
    placeholder: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    placeholderText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      marginTop: 10,
    },
    pressedState: {
      opacity: 0.7,
      transform: [{ scale: 0.98 }],
    },
    profileImage: {
      borderColor: theme.colors.onSurface,
      borderRadius: 65,
      borderWidth: 1,
      height: 130,
      width: 130,
    },
    profileImageContainer: {
      alignItems: 'center',
      marginBottom: 16,
      marginTop: 16,
      position: 'relative',
    },
    profileImageWrapper: {
      alignSelf: 'center',
      position: 'relative',
    },
    radio: {
      borderColor: theme.colors.primary,
      borderRadius: 10,
      borderWidth: 2,
      height: 20,
      marginTop: 6,
      width: 20,
    },
    radioGroup: {
      backgroundColor: theme.colors.backgroundOverlay,
      borderRadius: 32,
      marginBottom: 30,
      padding: 16,
    },
    radioSelected: {
      backgroundColor: theme.colors.primary,
    },
    safe: { backgroundColor: theme.colors.surface, flex: 1 },
    scrollContainer: {
      flexGrow: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingVertical: 16,
    },
    scrollView: {
      flex: 1,
    },
    searchBox: {
      backgroundColor: theme.colors.backgroundOverlay,
      borderColor: theme.colors.textSecondary,
      borderRadius: 16,
      borderWidth: 1.5,
      color: theme.colors.textPrimary,
      fontSize: 15,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    segmentedGroup: {
      backgroundColor: theme.colors.backgroundOverlay,
      borderRadius: 32,
      marginBottom: 30,
      marginTop: 20,
      padding: 10,
    },
    socialIcon: {
      alignItems: 'center',
      borderRadius: 25,
      elevation: 5,
      height: 50,
      justifyContent: 'center',
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      width: 50,
    },
    socialIconBase: {
      alignItems: 'center',
      borderRadius: 24,
      elevation: 3,
      height: 48,
      justifyContent: 'center',
      shadowColor: theme.colors.backdrop,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      width: 48,
    },
    socialIconsRow: {
      flexDirection: 'row',
      gap: 24,
      justifyContent: 'center',
      marginTop: 16,
    },
    socialMediaLink: {
      color: theme.colors.primary,
      fontSize: 14,
    },
    socialMediaText: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      lineHeight: 20,
    },
    subHeading: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '600',
      marginBottom: 8,
      marginTop: 12,
    },
    subtitle: {
      alignSelf: 'center',
      color: theme.dark ? theme.colors.onPrimary : theme.colors.textPrimary,
      fontSize: 14,
      marginBottom: 20,
    },
    switchLabel: {
      color: theme.colors.textPrimary,
      fontSize: 16,
    },
    switchRow: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 12,
      padding: 15,
    },
    text: {
      color: theme.colors.textPrimary,
      fontSize: 16,
    },
    textContainer: {
      flex: 1,
      marginTop: 15,
      paddingHorizontal: 10,
    },
    themeOptionRow: {
      alignItems: 'center',
      borderRadius: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginVertical: 4,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    themeOptionRowSelected: {
      backgroundColor: theme.colors.backgroundOverlay,
      borderColor: theme.colors.primary,
      borderWidth: 1,
    },
    themeOptionText: {
      color: theme.colors.textPrimary,
      fontSize: 16,
    },
    themeOptionTextSelected: {
      color: theme.colors.primary,
      fontWeight: '600',
    },
    themeOptionsContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: 10,
      marginTop: 20,
      padding: 8,
    },
    themeRadio: {
      borderColor: theme.colors.border,
      borderRadius: 10,
      borderWidth: 2,
      height: 20,
      width: 20,
    },
    themeRadioSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    themeToggleContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 20,
      padding: 15,
    },
    title: {
      alignSelf: 'center',
      color: theme.colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 20,
    },
    updateButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.onSurface,
      borderRadius: 25,
      marginBottom: 40,
      marginHorizontal: 30,
      paddingVertical: 15,
    },
    updateButtonText: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    username: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
      margin: 16,
    },
    versionButton: { alignItems: 'center', marginTop: 30, padding: 10 },

    versionText: { color: theme.colors.primary, fontWeight: 'bold' },
  });
};

export default useStyles;
