import { StyleSheet } from 'react-native';
import { ThemeType } from '../../theme';
import { overlays } from '../../../styles';

const useStyles = (theme: ThemeType) => {
  const styles = StyleSheet.create({
    button: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderRadius: 20,
      borderWidth: 2,
      flexDirection: 'row',
      marginHorizontal: 5,
      marginTop: 8,
      paddingHorizontal: 8,
      paddingVertical: 8,
    },
    buttonGroup: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginVertical: 5,
    },
    cardContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.textPrimary,
      borderRadius: 16,
      borderWidth: 1,
      elevation: 2,
      flexDirection: 'row',
      height: 160,
      marginVertical: 12,
      padding: 16,
    },
    cardImage: {
      height: '100%',
      resizeMode: 'cover',
      width: '100%',
    },
    cardText: {
      color: theme.colors.white,
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    cardTextContainer: {
      alignItems: 'center',
      bottom: 0,
      justifyContent: 'center',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
    },
    centerBlock: {
      alignItems: 'center',
      flex: 1,
      height: '100%',
      justifyContent: 'center',
    },
    closeButton: {
      padding: 5,
    },
    container: {
      backgroundColor: theme.colors.surface,
      flex: 1,
      padding: 15,
    },
    contentContainer: {
      flex: 1,
      marginLeft: 10,
    },
    descriptionText: {
      color: theme.colors.textPrimary,
      fontSize: 17,
      fontWeight: '500',
      lineHeight: 26,
      paddingVertical: 8,
      textAlign: 'left',
    },
    emptyContainer: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
      paddingBottom: 100,
    },
    emptyText: {
      color: theme.colors.textPrimary,
      fontFamily: theme.fonts.medium,
      fontSize: 18,
      textAlign: 'center',
    },
    equipmentOptions: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderRadius: 25,
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      width: '49%',
    },
    farSideBlock: {
      alignItems: 'center',
      flexDirection: 'column',
      height: '100%',
      justifyContent: 'space-between',
      marginLeft: 12,
    },
    favoriteFilterButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderColor: theme.colors.border,
      borderRadius: 16,
      borderWidth: 1,
      height: 32,
      justifyContent: 'center',
      width: 32,
    },
    favoriteFilterButtonActive: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    iconText: {
      alignItems: 'center',
      flexDirection: 'row',
    },
    image: {
      height: '100%',
      position: 'absolute',
      width: '100%',
    },
    imageBackground: {
      alignItems: 'center',
      flex: 1,
      height: 250,
      justifyContent: 'center',
      width: '100%',
    },
    imageLoadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      backgroundColor: overlays.hover.light,
      justifyContent: 'center',
    },
    imageWrapper: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderRadius: 16,
      justifyContent: 'center',
      overflow: 'hidden',
      width: 96,
    },
    info: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    infoContainer: {
      alignItems: 'center', // Dikey hizalama
      flexDirection: 'row', // Yan yana hizalama
      marginBottom: 10, // Alt boşluk
    },
    infoIcon: {
      marginRight: 6,
    },
    infoItem: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 4,
    },
    infoRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'flex-start',
      marginBottom: 6,
    },
    infoRowLeft: {
      alignItems: 'center',
      flexDirection: 'row',
      flex: 1,
    },
    infoText: {
      color: theme.colors.textSecondary,
      fontSize: 13,
    },
    loaderContainer: {
      alignItems: 'center',
      height: 300,
      justifyContent: 'center',
    },
    modalBackdrop: {
      alignItems: 'center',
      backgroundColor: theme.colors.backdrop,
      flex: 1,
      justifyContent: 'center',
      padding: 20,
      paddingVertical: 60,
    },
    modalContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: 24,
      elevation: 15,
      maxHeight: '85%',
      minHeight: 400,
      overflow: 'hidden',
      padding: 0,
      shadowColor: theme.colors.onSurface,
      shadowOffset: {
        width: 0,
        height: 15,
      },
      shadowOpacity: 0.3,
      shadowRadius: 25,
      width: '100%',
    },
    modalContent: {
      flex: 1,
      minHeight: 120,
      padding: 24,
      paddingBottom: 30,
      paddingTop: 20,
    },
    modalHeader: {
      alignItems: 'center',
      backgroundColor: theme.colors.secondary,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 24,
      paddingBottom: 16,
    },
    modalIcon: {
      marginRight: 12,
    },
    modalIconContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      flex: 1,
    },
    modalOverlay: {
      alignItems: 'center',
      backgroundColor: overlays.backdrop.light,
      flex: 1,
      justifyContent: 'center',
    },
    modalTitle: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 22,
      fontWeight: '800',
    },
    noDescriptionText: {
      color: theme.colors.textSecondary,
      fontSize: 17,
      fontStyle: 'italic',
      fontWeight: '500',
      paddingVertical: 20,
      textAlign: 'center',
    },
    optionButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.border,
      borderRadius: 25,
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      width: '32%',
    },
    optionIcon: {
      height: 20,
      marginRight: 8,
      resizeMode: 'contain',
      width: 20,
    },
    optionLabel: {
      color: theme.colors.black,
      fontSize: 14,
    },
    optionLabelSelected: {
      color: theme.colors.onPrimary,
    },
    optionSelected: {
      backgroundColor: theme.colors.primary,
    },
    overlay: {
      alignItems: 'center',
      backgroundColor: overlays.backdrop.light,
      height: '100%',
      justifyContent: 'center',
      position: 'absolute',
      width: '100%',
    },
    rankBadge: {
      alignItems: 'center',
      backgroundColor: theme.colors.accent,
      borderRadius: 20,
      height: 40,
      justifyContent: 'center',
      left: -10,
      position: 'absolute',
      shadowColor: theme.colors.accent,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      top: -10,
      width: 40,
    },
    rankText: {
      color: theme.colors.onPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    regionCard: {
      alignItems: 'center',
      aspectRatio: 1,
      borderColor: theme.colors.transparent,
      borderRadius: 12,
      borderWidth: 2,
      justifyContent: 'center',
      overflow: 'hidden',
      width: '30%',
    },
    regionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      justifyContent: 'space-between',
      marginVertical: 10,
    },
    scrollContent: {
      paddingBottom: 20,
    },
    selectedCard: {
      borderColor: theme.colors.primary,
    },
    selectedCardText:{
      color: theme.colors.white,
      fontWeight: 'bold',
    },
    selectedCardTextContainer:{
      backgroundColor: overlays.focus.light,
    },
    setCountIconWrapper: {
      alignItems: 'center',
      height: 36,
      justifyContent: 'center',
      position: 'relative',
      width: 36,
    },
    setCountImage: {
      alignItems: 'center',
      height: 80,
      justifyContent: 'center',
      paddingTop: 23,
      width: 80,
    },
    setCountOverlay: {
      color: theme.colors.textPrimary,
      fontSize: 12,
      fontWeight: '700',
      position: 'absolute', // 🔹 beyaz yerine siyah
    },
    setCountText: {
      color: theme.colors.onPrimary,
      fontSize: 14,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    sideBlock: {
      alignItems: 'center',
      height: '100%',
      justifyContent: 'center',
    },
    stepNumberContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 12,
      height: 24,
      justifyContent: 'center',
      width: 24,
    },
    stepNumberText: {
      color: theme.colors.textPrimary,
      fontSize: 12,
      fontWeight: 'bold',
    },
    summaryImage: {
      borderRadius: 16,
      height: 96,
      width: 96,
    },
    timeText: {
      color: theme.colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
    },
    title: {
      color: theme.dark ? theme.colors.onPrimary : theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '600',
      paddingTop: 8,
      textAlign: 'center',
    },
    video: {
      height: '100%',
      width: '100%',
    },
    videoContainer: {
      backgroundColor: theme.colors.onSurface,
      height: 600,
      width: '100%',
    },
    videoFail: {
      color: theme.colors.onPrimary,
      marginTop: 140,
      textAlign: 'center',
    },
    videoModalContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.googleRed,
      borderRadius: 24,
      elevation: 3,
      flex: 1,
      justifyContent: 'center',
      overflow: 'hidden',
      padding: 0,
      width: '90%',
    },
    videoModalContent: {
      backgroundColor: theme.colors.surfaceContainer,
      borderRadius: 24,
      elevation: 5,
      overflow: 'hidden',
      shadowColor: theme.colors.onSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      width: '92%',
    },
    videoModalExArea: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: 'bold',
    },
    videoModalTextXsmall: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: 'bold',
    },
    videoModalTextsmall: {
      color: theme.colors.textPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    videoModalTopArea: {
      alignItems: 'center',
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 15,
    },
  });
  return styles;
};

export default useStyles;
